# Parameters related to building hipFFT
ARG base_image

FROM ${base_image}
LABEL maintainer="hipfft-maintainer@amd.com"

ARG user_uid

# Install dependent packages
RUN zypper refresh && zypper -n install\
    sudo \
    ca-certificates \
    git \
    gcc-c++ \
    make \
    cmake \
    wget \
    rpm-build \
    dpkg \
    libboost_program_options1_66_0-devel\
    libcxxtools9 \
    libnuma1 \
    pkg-config 

#Compile FFTW
RUN cd ~/ && \
    wget http://fftw.org/fftw-3.3.8.tar.gz && \
    ls && \
    tar -xvf fftw-3.3.8.tar.gz && \
    cd fftw-3.3.8/ && \
    ./configure --prefix=/fftw --enable-openmp --enable-shared --enable-avx2 --enable-float && make -j && make install && \
    make clean && \
    ./configure --prefix=/fftw --enable-openmp --enable-shared --enable-avx2 && make -j && make install && \
    cd .. && \
    rm -rf fftw-*

# docker pipeline runs containers with particular uid
# create a jenkins user with this specific uid so it can use sudo priviledges
# Grant any member of sudo group password-less sudo privileges
RUN useradd --create-home -u ${user_uid} -o -G video --shell /bin/bash jenkins && \
    echo '%video ALL=(ALL) NOPASSWD:ALL' | tee /etc/sudoers.d/sudo-nopasswd && \
    chmod 400 /etc/sudoers.d/sudo-nopasswd

ARG ROCFFT_SRC_ROOT=/usr/local/src/rocFFT

# Clone rocfft repo
# Build client dependencies and install into /usr/local (LAPACK & GTEST)
RUN mkdir -p ${ROCFFT_SRC_ROOT} && cd ${ROCFFT_SRC_ROOT} && \
    git clone -b develop --depth=1 https://github.com/ROCmSoftwarePlatform/rocFFT . && \
    mkdir -p build/deps && cd build/deps && \
    cmake -DBUILD_BOOST=OFF ${ROCFFT_SRC_ROOT}/deps && \
    make -j $(nproc) install && \
    rm -rf ${ROCFFT_SRC_ROOT}
